title: Visionary Cross Project
email: jocelyn.mcknight@uleth.ca
description: >-
  Website of the Visionary Cross Project, hosted by the University of Lethbridge Humanities Innovation Lab.

baseurl: ""
url: "https://visionarycross.humanitiesinnovationlab.ca"

github_username: Jocelyn-McKnight

plugins:
  - jekyll-feed
